# ETL Pipeline Preparation
Follow the instructions below to help you create your ETL pipeline.
### 1. Import libraries and load datasets.
- Import Python libraries
- Load `messages.csv` into a dataframe and inspect the first few lines.
- Load `categories.csv` into a dataframe and inspect the first few lines.

In [2]:
# import libraries
import numpy as np
import pandas as pd
from sqlalchemy import create_engine

In [3]:
# load messages dataset
messages = pd.read_csv('messages.csv')
messages.head()

,id,message,original,genre
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct

In [6]:
# load categories dataset
categories = pd.read_csv('categories.csv')
categories.head()

   id                                         categories
0   2  related-1;request-0;offer-0;aid_related-0;medi...
1   7  related-1;request-0;offer-0;aid_related-1;medi...
2   8  related-1;request-0;offer-0;aid_related-0;medi...
3   9  related-1;request-1;offer-0;aid_related-1;medi...
4  12  related-1;request-0;offer-0;aid_related-0;medi...

### 2. Merge datasets.
- Merge the messages and categories datasets using the common id
- Assign this combined dataset to `df`, which will be cleaned in the following steps

In [7]:
# merge datasets
df = messages.merge(categories, left_on = 'id', right_on='id')
df.head()

,id,message,original,genre,categories
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct,related-1;request-0;offer-0;aid_related-0;medi...
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct,related-1;request-0;offer-0;aid_related-1;medi...
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct,related-1;request-0;offer-0;aid_related-0;medi...
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct,related-1;request-1;offer-0;aid_related-1;medi...
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct,related-1;request-0;offer-0;aid_related-0;medi...

### 3. Split `categories` into separate category columns.
- Split the values in the `categories` column on the `;` character so that each value becomes a separate column. You'll find [this method](https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.Series.str.split.html) very helpful! Make sure to set `expand=True`.
- Use the first row of categories dataframe to create column names for the categories data.
- Rename columns of `categories` with new column names.

In [8]:
# create a dataframe of the 36 individual category columns
categories = df['categories'].str.split(';',expand=True)
categories.head()

,0,1,2,3,4,5,6,7,8,9,...,26,27,28,29,30,31,32,33,34,35
0,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
1,related-1,request-0,offer-0,aid_related-1,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-1,floods-0,storm-1,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
2,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
3,related-1,request-1,offer-0,aid_related-1,medical_help-0,medical_products-1,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
4,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0

In [9]:
# select the first row of the categories dataframe
row = categories.iloc[0,:]

# use this row to extract a list of new column names for categories.
# one way is to apply a lambda function that takes everything 
# up to the second to last character of each string with slicing
category_colnames = row.apply(lambda x: x[:len(x) -2])
print(category_colnames)

0                    related
1                    request
2                      offer
3                aid_related
4               medical_help
5           medical_products
6          search_and_rescue
7                   security
8                   military
9                child_alone
10                     water
11                      food
12                   shelter
13                  clothing
14                     money
15            missing_people
16                  refugees
17                     death
18                 other_aid
19    infrastructure_related
20                 transport
21                 buildings
22               electricity
23                     tools
24                 hospitals
25                     shops
26               aid_centers
27      other_infrastructure
28           weather_related
29                    floods
30                     storm
31                      fire
32                earthquake
33                      cold
34             other_weather
35             direct_report
Name: 0, dtype: object

In [10]:
# rename the columns of `categories`
categories.columns = category_colnames
categories.head()

,related,request,offer,aid_related,medical_help,medical_products,search_and_rescue,security,military,child_alone,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
1,related-1,request-0,offer-0,aid_related-1,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-1,floods-0,storm-1,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
2,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
3,related-1,request-1,offer-0,aid_related-1,medical_help-0,medical_products-1,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0
4,related-1,request-0,offer-0,aid_related-0,medical_help-0,medical_products-0,search_and_rescue-0,security-0,military-0,child_alone-0,...,aid_centers-0,other_infrastructure-0,weather_related-0,floods-0,storm-0,fire-0,earthquake-0,cold-0,other_weather-0,direct_report-0

### 4. Convert category values to just numbers 0 or 1.
- Iterate through the category columns in df to keep only the last character of each string (the 1 or 0). For example, `related-0` becomes `0`, `related-1` becomes `1`. Convert the string to a numeric value.
- You can perform [normal string actions on Pandas Series](https://pandas.pydata.org/pandas-docs/stable/text.html#indexing-with-str), like indexing, by including `.str` after the Series. You may need to first convert the Series to be of type string, which you can do with `astype(str)`.

In [11]:
for column in categories:
    # set each value to be the last character of the string
    categories[column] = categories[column].astype(str).str[-1]
    
    # convert column from string to numeric
    categories[column] = categories[column].astype(int)
categories.head()

,related,request,offer,aid_related,medical_help,medical_products,search_and_rescue,security,military,child_alone,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,1,0,0,0,0,0,0,...,0,0,1,0,1,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### 5. Replace `categories` column in `df` with new category columns.
- Drop the categories column from the df dataframe since it is no longer needed.
- Concatenate df and categories data frames.

In [12]:
# drop the original categories column from `df`
df.drop(['categories'], axis=1, inplace=True)

df.head()

,id,message,original,genre
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct

In [13]:
# concatenate the original dataframe with the new `categories` dataframe
df = pd.concat([df, categories], axis=1, join='inner', sort=False)
df.head()

,id,message,original,genre,related,request,offer,aid_related,medical_help,medical_products,...,aid_centers,other_infrastructure,weather_related,floods,storm,fire,earthquake,cold,other_weather,direct_report
0,2,Weather update - a cold front from Cuba that c...,Un front froid se retrouve sur Cuba ce matin. ...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,Is the Hurricane over or is it not over,Cyclone nan fini osinon li pa fini,direct,1,0,0,1,0,0,...,0,0,1,0,1,0,0,0,0,0
2,8,Looking for someone but no name,"Patnm, di Maryani relem pou li banm nouvel li ...",direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9,UN reports Leogane 80-90 destroyed. Only Hospi...,UN reports Leogane 80-90 destroyed. Only Hospi...,direct,1,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,12,"says: west side of Haiti, rest of the country ...",facade ouest d Haiti et le reste du pays aujou...,direct,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### 6. Remove duplicates.
- Check how many duplicates are in this dataset.
- Drop the duplicates.
- Confirm duplicates were removed.

In [14]:
df.shape[0]

26386

In [15]:
# check number of duplicates
df.duplicated().sum()

170

In [16]:
# drop duplicates
df.drop_duplicates(keep='first', inplace=True)

In [17]:
df.shape[0]

26216

In [18]:
# check number of duplicates
df.duplicated().sum()

0

In [28]:
for column in df.columns:
    print(df[column].value_counts())

17553    2
27768    2
19003    2
24247    2
1652     2
14135    2
6393     2
7747     2
13914    2
28462    2
15760    2
19142    2
12420    2
12416    2
16245    2
18925    2
19687    2
11503    2
25512    2
202      2
862      2
24347    2
6492     2
29022    2
7945     2
17385    2
22858    2
8190     2
6515     2
6687     2
        ..
19196    1
23294    1
21247    1
11024    1
2772     1
13011    1
15058    1
8913     1
661      1
6806     1
4759     1
27288    1
25241    1
19100    1
17053    1
23198    1
21151    1
15026    1
12979    1
2740     1
6838     1
4791     1
27320    1
25273    1
29371    1
17085    1
23230    1
21183    1
10960    1
2049     1
Name: id, Length: 26180, dtype: int64
#NAME?                                                                                                                                                                                                                                                                                                                                                                                                                                                        4
I can help deliver food to seniors who are trapped in their homes . I speak Mandarin and Cantonese .                                                                                                                                                                                                                                                                                                                                                          2
What can i do to protect my self if the earthquake comes back?                                                                                                                                                                                                                                                                                                                                                                                                2
In a field in Jallouzai, just inside Pakistan, 80,000 Afghans are jammed in without proper shelter, sanitation or water.                                                                                                                                                                                                                                                                                                                                      2
in my village after collapse of whole infrastructure due to flood the majority of people is homeless  in need of tents which are not available.                                                                                                                                                                                                                                                                                                               2
Tell the President to give the nation over to God.                                                                                                                                                                                                                                                                                                                                                                                                            2
As we approach Luabo, I get my first impressions of the camp, dilapidated buildings, most without roofs, or windows and walls collapsing.                                                                                                                                                                                                                                                                                                                     2
I'd like to know an email to find a job                                                                                                                                                                                                                                                                                                                                                                                                                       2
What we saw yesterday is a sign, you need to know what Jesus is stirring up/doing                                                                                                                                                                                                                                                                                                                                                                             2
The last locust infestation in the Central Asian republic was in 1995 and is expected to reoccur every four to five years.                                                                                                                                                                                                                                                                                                                                    2
HELP THE EARTHQUAKE VICTIMS IN HAITI http tinyurl.com yk3bspe links to many resources where you can make donations. Broke? donate time                                                                                                                                                                                                                                                                                                                        2
Before we take your general questions, I'd like to make a few opening remarks concerning ISAF support to the Afghan people during these frigid winter months. After the earthquake, huge boulders blocked off the road to large vehicles. Most years, floods wreak havoc in the state, leaving a trail of destruction and killing hundreds of people. We have heard of crocodile sightings.                                                                   2
They reported sporadic rains were still flooding air fields, roads and slowing urgent repairs along several key highways.                                                                                                                                                                                                                                                                                                                                     2
where we can paticipate in the law reorganizations?                                                                                                                                                                                                                                                                                                                                                                                                           2
Some herders now have their homes connected to the town grid or, in the most isolated areas, herders have been provided with solar panels and small wind turbine systems as sources of renewable energy.                                                                                                                                                                                                                                                      2
here,i'm i don't find medicin just resting to die where i can find it?                                                                                                                                                                                                                                                                                                                                                                                        2
What is the address of the radio station? I ask because I need to drop off a file for the committee we created. Thanks in advance!                                                                                                                                                                                                                                                                                                                            2
On behalf of ACT members in Bangladesh Christian Commission for Development in Bangladesh (CCDB) and Rangpur Dinajpur Rural Service (RDRS) - LWF/WS report that none of their projects has yet been affected but that the low-lying areas of the north-eastern districts have been inundated by an on-rush of floodwater from across the border following rains and overflowing rivers in the neighbouring Indian state of Assam.                             2
I'd like to sign up in the 4636 program please                                                                                                                                                                                                                                                                                                                                                                                                                2
It was offshore about 130 km to the southeast of Wenchang City on the east coast of Hainan and packing wind of up to force 8.                                                                                                                                                                                                                                                                                                                                 2
As the harsh winter sets in, more people are in danger of dying in the freezing conditions.                                                                                                                                                                                                                                                                                                                                                                   2
An EU-backed French offensive against rebels restored an uneasy order, but foreign donors have insisted on the elections before aid is resumed to Mali.                                                                                                                                                                                                                                                                                                       2
Falta tan tan poco.. ¬¨¬¥Simply Red - Holding back the years¬¨¬™. Arena Santiago, de all‚àö¬∞ somos! Night.  http://blip.fm/~n0frf                                                                                                                                                                                                                                                                                                                            2
In response to North Korea's devastating artillery attack on Yeonpyeong Island on Tuesday, South Korea has suspended aid shipments of food and cement to the North's flood-stricken Shinuiju region.                                                                                                                                                                                                                                                          2
Me and my family every time it rains you do not know what to do, because we have nothing to shelter, please find us something that we live in a military cites the legal street pole.                                                                                                                                                                                                                                                                         2
To date, a total of 39 people suffering from Ebola or having had a high risk exposure to the virus, have been medically evacuated to Europe.                                                                                                                                                                                                                                                                                                                  2
World Vision staff stationed in Jabouri immediately reached the mudslide area to offer assistance.                                                                                                                                                                                                                                                                                                                                                            2
The flood situation has worsened with nearly 3,000 villages submerged forcing an estimated 150,000 people to take shelter in raised platforms and makeshift tarpaulin tents, Assam Revenue, Relief and Rehabilitation Minister Bhumidhar Barman said.                                                                                                                                                                                                         2
I am in Carefour Feuilles, Dkayet neighborhood. We need potable water because diarrhea is rampant here and is undermining our health.                                                                                                                                                                                                                                                                                                                         2
Any person who enters or exits at other points will be considered an infiltrator, he added.                                                                                                                                                                                                                                                                                                                                                                   2
                                                                                                                                                                                                                                                                                                                                                                                                                                                             ..
How long time can we expect for the replies?                                                                                                                                                                                                                                                                                                                                                                                                                  1
Several hundred thousands of homes were washed away when wind-driven tidal surges up to 3 meters destroyed the coastal belt.                                                                                                                                                                                                                                                                                                                                  1
NOTES: This person is playing.                                                                                                                                                                                                                                                                                                                                                                                                                                1
Sprawling refugee camps have sprung up recently in the parched deserts of East Africa to handle the mass exodus from famine-stricken Somalia.                                                                                                                                                                                                                                                                                                                 1
This appeal currently focuses on emergency needs in Ghana, where excessive rainfall coupled with the spillage of excess water from the Bagre Reservoir in Burkina Faso has resulted in extensive floods in the Northern, Upper East and Upper West Regions.                                                                                                                                                                                                   1
Urine can be used directly as fertilizer because its nitrate content replenishes nutrients in the soil, but solid waste is stored in one of the toilet's two chambers for a period of six months, neutralizing dangerous bacteria.                                                                                                                                                                                                                            1
The report accused the Zimbabwean government of ignoring the country's constitution and laws by failing to enforce judicial rulings ordering violent occupiers off white-owned farms.                                                                                                                                                                                                                                                                         1
"It is time for Malawi to move beyond the fertilizer-led "green revolution" and invest in the Brown and Blue Revolutions needed to rebuild soil fertility and water retention," the Special Rapporteur urged.                                                                                                                                                                                                                                                 1
What a tragedy in #Haiti with the earthquake. My friend knows someone well at the UN compound where much staff is missing.                                                                                                                                                                                                                                                                                                                                    1
In addition, we urge all parties to ensure neutral, impartial, and unhindered humanitarian access to all populations in northern Mali The United States continues to support the leadership of the Economic Community of West African States (ECOWAS) in its mediation efforts and will continue to consult with ECOWAS and other regional stakeholders on the best way to facilitate the political transition and restore peace and security across Mali.    1
In eastern Africa, poor rains and the lingering effects of past droughts and conflicts have increased the likelihood of serious food shortages in several countries.                                                                                                                                                                                                                                                                                          1
Location - Anse A Galets, La Gonave, near Wesleyenne Hospital, Need assistance fixing the school and also feeding 500 children.                                                                                                                                                                                                                                                                                                                               1

In [ ]:
# fix 2 values in related
df.related.replace(2,1,inplace=True)

### 7. Save the clean dataset into an sqlite database.
You can do this with pandas [`to_sql` method](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_sql.html) combined with the SQLAlchemy library. Remember to import SQLAlchemy's `create_engine` in the first cell of this notebook to use it below.

In [32]:
engine = create_engine('sqlite:///InsertDatabaseName.db')
df.to_sql('InsertTableName', engine, index=False)

### 8. Use this notebook to complete `etl_pipeline.py`
Use the template file attached in the Resources folder to write a script that runs the steps above to create a database based on new datasets specified by the user. Alternatively, you can complete `etl_pipeline.py` in the classroom on the `Project Workspace IDE` coming later.